namespace VakunTranslatorVol2
{
    public enum LexemeCodes
    {
        UNDEFINED = -1,
        PROGRAM = 0,
        FLOAT = 1,
        INT = 2,
        LABEL = 3,
        LEFT_BRACE = 4,
        RIGHT_BRACE = 5,
        SEMICOLON = 6,
        COMMA = 7,
        LEFT_PARENTHESIS = 8,
        RIGHT_PARENTHESIS = 9,
        QUESTION_MARK = 10,
        COLON = 11,
        IF = 12,
        ELSE = 13,
        THEN = 14,
        WHILE = 15,
        DO = 16,
        FOR = 17,
        ASSIGN = 18,
        READ = 19,
        WRITE = 20,
        LESS_THAN = 21,
        MORE_THAN = 22,
        LESS_EQUAL = 23,
        MORE_EQUAL = 24,
        PLUS = 25,
        MINUS = 26,
        MULTIPLY = 27,
        DIVISION = 28,
        AND = 29,
        OR = 30,
        EQUAL = 31,
        NOT_EQUAL = 32,
        NOT = 33,
        TO = 34,
        BY = 35,
        END = 36,
        GOTO = 37,
        CONSTANT = 38,
        ID = 39,
    }
}